platform :ios, '10.0'
use_frameworks!

def shared_pods
  
  pod 'GoogleSignIn'
  pod 'ProgressHUD'
  pod 'Alamofire', '~> 5.0.0-beta.5'
end

target 'demoCaptureImage' do
  # Pods for demoCaptureImage
  shared_pods
end

target 'demoCaptureImageTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'demoCaptureImageUITests' do
  inherit! :search_paths
  # Pods for testing
end
