# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoCaptureImage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for demoCaptureImage
  pod 'GoogleSignIn'
  pod 'AFNetworking', '~> 3.0'
  pod 'ProgressHUD'

  target 'demoCaptureImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoCaptureImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
