platform :ios, '10.0'
use_frameworks!

def shared_pods
  
  pod 'GoogleSignIn'
  pod 'ProgressHUD'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'FSPagerView'
  
end

target 'demoCaptureImage' do
  # Pods for demoCaptureImage
  shared_pods
end
